services:
  mysql:
    image: mysql:8.0
    container_name: mysql_payment_gateway
    environment:
      MYSQL_DATABASE: payment_gateway
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    command: ["--default-authentication-plugin=mysql_native_password"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql

  payment-gateway:
    build: .
    container_name: payment_gateway_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/payment_gateway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_FLYWAY_ENABLED: "true"
      PROVIDER_MOCK_LATENCY_MS: "50"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: